/**
 * WebScanPage — public QR scan page for third-party drivers (UberDirect/DoorDash).
 *
 * URL format: /scan?token=BASE64_JSON
 * Token payload: { orderId, step, fromUserId, toUserId, bagId, expires }
 *
 * No user authentication required. The token is generated by the dispatch-driver
 * Edge Function and is valid for 4 hours. Server-side validation happens in the
 * Supabase Edge Function on submission.
 */
import { useState, useEffect } from 'react'
import { useSearchParams } from 'react-router-dom'
import { CheckCircle, AlertCircle } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { QRScannerModal } from '@/components/shared/QRScanner/QRScannerModal'
import { PhotoCaptureModal } from '@/components/shared/PhotoCapture/PhotoCaptureModal'
import { supabase, storage } from '@/lib/supabase'
import type { WebScanToken } from '@/types/driver.types'

type PageState = 'loading' | 'ready' | 'scanning' | 'photo' | 'submitting' | 'success' | 'error' | 'expired'

function decodeToken(raw: string): WebScanToken | null {
  try {
    return JSON.parse(atob(raw)) as WebScanToken
  } catch {
    return null
  }
}

const STEP_LABELS: Record<string, string> = {
  customer_to_driver: 'Pickup from Customer',
  hub_to_driver:      'Pickup from Hub',
  driver_to_customer: 'Deliver to Customer',
  driver_to_hub:      'Return to Hub',
}

export function WebScanPage() {
  const [searchParams] = useSearchParams()
  const rawToken = searchParams.get('token') ?? ''

  const [pageState, setPageState] = useState<PageState>('loading')
  const [token, setToken] = useState<WebScanToken | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [scannedQr, setScannedQr] = useState<string | null>(null)
  const [orderNumber, setOrderNumber] = useState<string | null>(null)

  useEffect(() => {
    if (!rawToken) {
      setError('Missing scan token. Use the link provided by LaundrLink.')
      setPageState('error')
      return
    }

    const decoded = decodeToken(rawToken)
    if (!decoded) {
      setError('Invalid scan token. Please use the original link.')
      setPageState('error')
      return
    }

    if (decoded.expires < Date.now()) {
      setPageState('expired')
      return
    }

    setToken(decoded)

    // Fetch order number for display
    Promise.resolve(
      supabase
        .from('orders')
        .select('order_number')
        .eq('id', decoded.orderId)
        .single()
    )
      .then(({ data }) => {
        if (data) setOrderNumber(data.order_number)
      })
      .catch(() => {/* display is optional */})

    setPageState('ready')
  }, [rawToken])

  const handleScan = (qr: string) => {
    setScannedQr(qr)
    setPageState('photo')
  }

  const handlePhotos = async (photos: File[]) => {
    if (!token) return
    setPageState('submitting')
    setError(null)

    try {
      // Upload photos to Supabase Storage using anon key
      const photoUrls: string[] = []
      for (let i = 0; i < photos.length; i++) {
        const ext = photos[i].name.split('.').pop() ?? 'jpg'
        const path = `${token.orderId}/web-scan-${Date.now()}/${i}.${ext}`
        const { error: uploadErr } = await storage.handoffPhotos.upload(path, photos[i], {
          contentType: photos[i].type,
          upsert: true,
        })
        if (uploadErr) throw uploadErr
        const { data } = storage.handoffPhotos.getPublicUrl(path)
        photoUrls.push(data.publicUrl)
      }

      // Call edge function for server-side token validation + handoff creation
      const { error: fnErr } = await supabase.functions.invoke('scan-handoff-public', {
        body: {
          token: rawToken,
          qr_code: scannedQr,
          photo_urls: photoUrls,
        },
      })

      if (fnErr) throw fnErr

      setPageState('success')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Submission failed. Please try again.')
      setPageState('error')
    }
  }

  // ── Render states ────────────────────────────────────────────────────────────

  if (pageState === 'loading') {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <p className="text-gray-400 animate-pulse">Loading…</p>
      </div>
    )
  }

  if (pageState === 'expired') {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6 text-center">
        <AlertCircle className="h-12 w-12 text-amber-500 mb-4" />
        <h1 className="text-xl font-bold text-gray-900 mb-2">Link Expired</h1>
        <p className="text-gray-500 text-sm">
          This scan link has expired (valid for 4 hours). Contact the hub for a new link.
        </p>
      </div>
    )
  }

  if (pageState === 'error') {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6 text-center">
        <AlertCircle className="h-12 w-12 text-red-500 mb-4" />
        <h1 className="text-xl font-bold text-gray-900 mb-2">Something went wrong</h1>
        <p className="text-gray-500 text-sm mb-6">{error}</p>
        <Button variant="outline" onClick={() => { setError(null); setPageState('ready') }}>
          Try Again
        </Button>
      </div>
    )
  }

  if (pageState === 'success') {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6 text-center">
        <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mb-4">
          <CheckCircle className="h-10 w-10 text-green-600" />
        </div>
        <h1 className="text-2xl font-bold text-gray-900 mb-2">Handoff Recorded</h1>
        <p className="text-gray-500">
          {orderNumber ? `Order #${orderNumber}` : 'Order'} — {STEP_LABELS[token?.step ?? ''] ?? token?.step}
        </p>
        <p className="text-gray-400 text-sm mt-1">You can close this window.</p>
      </div>
    )
  }

  if (pageState === 'submitting') {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6 text-center">
        <p className="text-indigo-600 animate-pulse text-lg font-medium">Uploading and recording…</p>
      </div>
    )
  }

  // ready or scanning/photo (modals handle those)
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* LaundrLink branding header */}
      <div className="bg-white border-b border-gray-100 px-4 py-4 flex items-center gap-3">
        <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center">
          <span className="text-white text-xs font-bold">LL</span>
        </div>
        <p className="font-semibold text-gray-900">LaundrLink Delivery Scan</p>
      </div>

      <div className="flex-1 p-6 flex flex-col gap-4">
        {/* Order info */}
        <Card className="rounded-2xl border-0 shadow-sm">
          <CardContent className="p-5">
            <p className="text-xs text-gray-500 uppercase tracking-wider font-medium mb-1">
              {STEP_LABELS[token?.step ?? ''] ?? token?.step}
            </p>
            {orderNumber && (
              <p className="text-lg font-bold text-gray-900">Order #{orderNumber}</p>
            )}
            <p className="text-sm text-gray-500 mt-1">
              Scan the QR code on the laundry bag, then take a photo as proof.
            </p>
          </CardContent>
        </Card>

        {/* Instructions */}
        <div className="space-y-2">
          {[
            { n: '1', text: 'Tap the button below to open your camera' },
            { n: '2', text: 'Point the camera at the QR code on the bag tag' },
            { n: '3', text: 'Take a photo of the bag as proof of handoff' },
          ].map(({ n, text }) => (
            <div key={n} className="flex items-start gap-3">
              <div className="w-6 h-6 bg-indigo-100 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                <span className="text-indigo-600 text-xs font-bold">{n}</span>
              </div>
              <p className="text-sm text-gray-600">{text}</p>
            </div>
          ))}
        </div>

        <Button
          className="w-full h-14 rounded-2xl text-base mt-auto"
          onClick={() => setPageState('scanning')}
        >
          Open Camera & Scan Bag
        </Button>

        <p className="text-center text-xs text-gray-400">
          Powered by LaundrLink — laundry delivered to your door.
        </p>
      </div>

      <QRScannerModal
        isOpen={pageState === 'scanning'}
        onClose={() => setPageState('ready')}
        onScan={handleScan}
        title="Scan Bag QR Code"
      />

      <PhotoCaptureModal
        isOpen={pageState === 'photo'}
        onClose={() => setPageState('ready')}
        onCapture={(photos) => void handlePhotos(photos)}
        maxPhotos={2}
      />
    </div>
  )
}
